# Generated by Django 4.1.5 on 2023-01-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_banner_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='banner', verbose_name='广告图片'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(max_length=500, verbose_name='广告链接'),
        ),
    ]
